version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      - DATABASE_PW=${DB_PASSWORD}
      - PORT=5432
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db