version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  db:
    image: postgres
    networks:
      - app_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PW}  # Consistent reference to DATABASE_PW
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app1:
    build: .
    networks:
      - app_network
    env_file:
      - .env  # Reference the .env file here
    environment:
      - DATABASE_PW=${DATABASE_PW}  # Ensure DATABASE_PW is correctly passed
      - PORT=5432
      - DATABASE_URL=postgresql://postgres:${DATABASE_PW}@db:5432/dbname  # PostgreSQL connection string
    command: ["python", "launch_tg.py"]
    depends_on:
      - db
    links:
      - db

  app2:
    build: .
    networks:
      - app_network
    env_file:
      - .env  # Reference the .env file here
    environment:
      - DATABASE_PW=${DATABASE_PW}  # Ensure DATABASE_PW is consistently used
      - PORT=5432
      - DATABASE_URL=postgresql://postgres:${DATABASE_PW}@db:5432/dbname  # PostgreSQL connection string
    command: ["python", "launch_ds.py"]
    depends_on:
      - db
    links:
      - db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus config
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app_network

    # Grafana service (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app_network
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  pgdata: