version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PW}  # Consistent reference to DATABASE_PW
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app1:
    build: .
    env_file:
      - .env  # Reference the .env file here
    environment:
      - DATABASE_PW=${DATABASE_PW}  # Ensure DATABASE_PW is correctly passed
      - PORT=5432
    command: ["python", "launch_tg.py"]
    depends_on:
      - db
    links:
      - db

  app2:
    build: .
    env_file:
      - .env  # Reference the .env file here
    environment:
      - DATABASE_PW=${DATABASE_PW}  # Ensure DATABASE_PW is consistently used
      - PORT=5432
    command: ["python", "launch_ds.py"]
    depends_on:
      - db
    links:
      - db