global:
  scrape_interval: 15s  # How often to scrape metrics
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  - job_name: 'discord_bot'
    static_configs:
      - targets: ['discord_bot:5000']  # Replace with the exposed metrics endpoint of your bot

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Monitor Prometheus itself
